# Generated by Django 3.1.6 on 2024-01-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
    ]
